// Write code below 💖

console.log('==========================================================')
console.log('                     JERONIMO BURGER                      ')
console.log('==========================================================')
console.log('                      ORDER DETAILS                       ')
console.log('----------------------------------------------------------')
console.log('Item                              Quantity         Price  ')
console.log('----------------------------------------------------------')
console.log('🍔 Burger                            1             2.99   ')
console.log('🍟 Fries                             1             1.99   ')
console.log('🥤 Soda                              1             0.99   ')
console.log('----------------------------------------------------------')
console.log('Total:                               3             5.97   ')
console.log('==========================================================')